### ISSUE TITLE
docker-compose upでコンテナを立ち上げた時に、標準入力が正常に受け取れない理由

### ISSUE THREAD

**Issue by yuyakawai0411** [yuyakawai0411/openai_test#2]
## 状況
docker-composeを以下のように定義し、docker-compose upでコンテナを立ち上げた。
その後、ターミナルで入力を渡したが、script.pyに定義した`input()`関数が待機したままになっていた。

*docker-compose.yml*
```
version: "3.9"
services:
  web:
    build: .
    stdin_open: true # コンテナの標準入力を開いた状態にする
    # フォアグラウンドで動くプロセスがないため、コンテナの立ち上げ状態を維持するためtty: trueを指定する
    # CLIの操作を可能にする
    tty: true
    command: python script.py
    volumes:
      - .:/myapp

```

*scipt.py*
```python
from dotenv import dotenv_values
from openai import OpenAI

client = OpenAI(
  api_key=dotenv_values(".env").get("OPENAI_API_KEY")
)

prompt = input()

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": prompt}
  ]
)

print(completion.choices[0].message.content)

```

##
